<?php 

class view_demo_function_prefix{ 

public function M($V){ 
extract($V);
$_ ='';
$_ .= ' ouput string length of sub-string "hello,worlds": <br /> ';
 $_ .=  htmlspecialchars( strlen  ( substr("hello,worlds",0,10))  ); 
$_ .= ' <hr /> ';
 $_ .=  
substr("<h1>hello,worlds</h1>",0 ,100 )
  ; 
$_ .= ' ';
  

$obj =new stdClass();
$obj->id=1;
$_ .= $obj->id;


$t = new Test();
$_ .= $t->a();

$_ .= Test::b();

  

return $_;
} 


}  ?>